---
version: "3"
services:
  netalertx:
    container_name: netalertx
    # use the below line if you want to test the latest dev image
    # image: "ghcr.io/jokob-sk/netalertx-dev:latest" 
    image: "ghcr.io/jokob-sk/netalertx:latest"      
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - /opt/netalertx/docker_appdata/:/app/config
      - /opt/netalertx/docker_appdata/db/:/app/db/      
      # (optional) useful for debugging if you have issues setting up the container
      - /opt/netalertx/docker_logs:/app/log
      # (API: OPTION 1) use for performance
      - type: tmpfs
        target: /app/api
      # (API: OPTION 2) use when debugging issues 
       -  /opt/netalertx/docker_api/:/app/api
    environment:
      - TZ=Asia/Bangkok     
      - PORT=20211
